// Code Generated by Sidekick is for learning and experimentation purposes only.
// filename: Services/ReservationServiceClient.cs
using System.Text.Json;
using UserService.DTOs;

namespace UserService.Services;

public class ReservationServiceClient : IReservationServiceClient
{
    private readonly HttpClient _httpClient;
    private readonly ILogger<ReservationServiceClient> _logger;

    // JsonSerializerOptions that accepts both camelCase and PascalCase property names.
    private static readonly JsonSerializerOptions _jsonOptions = new()
    {
        PropertyNameCaseInsensitive = true
    };

    public ReservationServiceClient(HttpClient httpClient, ILogger<ReservationServiceClient> logger)
    {
        _httpClient = httpClient;
        _logger = logger;
    }

    public async Task<ReservationStatisticsDto?> GetStatisticsAsync(Guid userId)
    {
        try
        {
            var response = await _httpClient.GetAsync($"/api/reservations/statistics/{userId}");

            if (!response.IsSuccessStatusCode)
            {
                _logger.LogWarning(
                    "Reservation Service returned {StatusCode} for statistics/{UserId}",
                    (int)response.StatusCode, userId);
                return null;
            }

            var content = await response.Content.ReadAsStringAsync();
            return JsonSerializer.Deserialize<ReservationStatisticsDto>(content, _jsonOptions);
        }
        catch (HttpRequestException ex)
        {
            _logger.LogWarning(ex,
                "Reservation Service is unavailable while fetching statistics for user {UserId}", userId);
            return null;
        }
        catch (TaskCanceledException ex)
        {
            _logger.LogWarning(ex,
                "Reservation Service timed out while fetching statistics for user {UserId}", userId);
            return null;
        }
    }
}